### ISSUE TITLE
Bokeh plots

### ISSUE THREAD

**Issue by agitter** [jgmeyerucsd/drug-class#3]
If you want to host Bokeh plots like `test.html` in this repository, you may be able to do it directly with [GitHub Pages](https://help.github.com/categories/github-pages-basics/).  That way the HTML will be rendered.

We have examples of using GitHub Pages through the `gh-pages` branch in the repository.

**Comment by jgmeyerucsd** [comment]
Decided to delete the bokeh plot html for now to keep the repo clean. Will try using github pages in the future, thank you.
